### ISSUE TITLE
Use multiple buttons in one project

### ISSUE THREAD

**Issue by alkurop** [ubieda/zephyr_button_debouncing#2]
Hi. How do I used this code with multiple buttons?

**Comment by ubieda** [comment]
Hi, thanks for reaching out!

The software debouncing functionality is already integrated in the zephyr gpio-keys driver (see: https://github.com/zephyrproject-rtos/zephyr/pull/52698). I suggest you use that, instead.

**Comment by alkurop** [comment]
Thanks :) Is there an example on how to use it?

**Comment by ubieda** [comment]
Sure - Just make sure you define `debounce-interval-ms` on the device-tree and it should _just_ work. Here's a test showcasing this:
https://github.com/zephyrproject-rtos/zephyr/blob/9a08fdc1df5c000b54a1df2ec014207df282768d/tests/drivers/input/gpio_keys/boards/native_sim.overlay#L14

**Comment by alkurop** [comment]
Just to make sure, I have a esp32c3. My code here:
```
   gpio_pin_interrupt_configure_dt(&button, GPIO_INT_EDGE_BOTH);
    gpio_init_callback(&button_cb_data, button_pressed, BIT(button.pin));
    gpio_add_callback(button.port, &button_cb_data);

```
I want 2 events - on press, and on release.

Overlay is this

```
/ {
	compatible = "espressif,esp32";
	aliases {
		led0 = &led0;
		sw0 = &button0;
	};

	leds {
		compatible = "gpio-leds";
		led0: led_0 {
			gpios = <&gpio0 0 GPIO_ACTIVE_LOW>;
		};
	};
	buttons {
		compatible = "gpio-keys";
		debounce-interval-ms = <30>;
		button0: button_0 {
			gpios = <&gpio0 1 (GPIO_PULL_UP | GPIO_ACTIVE_LOW)>;
			label = "Push button switch 0";
		};
	};
};

&uart0 {
	zephyr,deferred-init;
};

```

The I don't see any difference with the debouncing  - it seems like it's not working. Maybe I misconfigured something?

**Comment by ubieda** [comment]
The debouncing goes under each button node. See this for reference:

```
/ {
	buttons {
		compatible = "gpio-keys";

		button0: button_0 {
			/** The debouncing goes under every button - here */
			debounce-interval-ms = <30>;
		};

		button1: button_1 {
			/** The debouncing goes under every button - here */
			debounce-interval-ms = <100>;
		};

	};
};
```

**Comment by alkurop** [comment]
Once I moved the `debounce ` into button, it won't compile 
![Screenshot 2024-06-28 at 22 29 27](https://github.com/ubieda/zephyr_button_debouncing/assets/5940685/f3f4d677-ad40-45d8-aaf8-20465b245a9c)
And also here it's a top level property https://docs.zephyrproject.org/latest/build/dts/api/bindings/input/gpio-keys.html

**Comment by ubieda** [comment]
Apologies, I just double-checked and it does go as you had it before.

**Comment by ubieda** [comment]
Make sure you're using the Input subsystem, as the attached test does (not the regular GPIO API)

**Comment by alkurop** [comment]
Just to confirm, I had to do several changes:
1. `proj.config` -> add `CONFIG_INPUT=y`
2. in Main, I removed all the code for button, and instead added this code

```
#include <zephyr/input/input.h>

void button_pressed(struct input_event *evt)
{
    printk("PRESSED\n");
}

int main(void)
{
    INPUT_CALLBACK_DEFINE(NULL, button_pressed);
}
```

Also I added a code for button, otherwise it will not compile.

```
button0: button_0 {
			gpios = <&gpio0 1 (GPIO_PULL_UP | GPIO_ACTIVE_LOW)>;
this line --->	zephyr,code = <10>;
			label = "Push button switch 0";
		};
```

All works :) Both for press, and release. 
Thank you

**Comment by ubieda** [comment]
Great!

Closing issue as resolved

**Comment by alkurop** [comment]
One more question - can I use this button to wake up device with Power Management?
